### ISSUE TITLE
Implementação de impressao

### ISSUE THREAD

**Issue by Guimarte** [gabuldev/pagseguro_smart_flutter#13]
Ao implementar a nova impressão de arquivos, estou tendo alguns problemas 
![image](https://github.com/gabuldev/pagseguro_smart_flutter/assets/66447422/8bd44653-ca2a-4143-8100-92455919caa0)

Nessa imagem acima, da maneira padrão

![image](https://github.com/gabuldev/pagseguro_smart_flutter/assets/66447422/cb1a1044-d43e-4987-81b8-71b187be4b93)
Na imagem acima percebi que o printFromFile não envia o path para o nativo, ai depois que implementei o path, deu o erro na imagem abaixo:

![image](https://github.com/gabuldev/pagseguro_smart_flutter/assets/66447422/168276e0-5dbb-482e-9ed5-1c8ac835bef0)

Estou tentando imprimir uma NFC-E que está em pdf.

**Comment by jhonathanqz** [comment]
Uma nova PR foi aberta para correção do método.
A única informação que você deve passar como parâmetro na função é o PATH ABSOLUTO do arquivo que deseja imprimir.

**Comment by Guimarte** [comment]
> Uma nova PR foi aberta para correção do método. A única informação que você deve passar como parâmetro na função é o PATH ABSOLUTO do arquivo que deseja imprimir.

Muito obrigado, fico no aguardo da a liberação e atualizacao do package.

**Comment by muriloventuroso** [comment]
@jhonathanqz estou tendo o mesmo problema mesmo utilizando a sua versão com a correção

```
I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: No Key event currently.
I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: Previeous Event null,finish at 1969-12-31 21:00:00.000
I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: No motion event currently.
I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: Previeous Event MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=365.0, y[0]=1211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100231397, downTime=100231307, deviceId=0, source=0x1002 },finish at 2024-05-14 19:15:24.354
I/art     (15174): Thread[3,tid=15180,WaitingInMainSignalCatcherLoop,Thread*=0xa03cb300,peer=0x12cc6b80,"Signal Catcher"]: reacting to signal 3
I/art     (15174): 
I/art     (15174): Wrote stack traces to '/data/anr/traces.txt'
I/art     (15174): ::: 84262ec 9e856d bb31492 94208d 9bfbd7c
I/art     (15174): ::: 6f25558 ad72bf9 264a0f0 4bd579f 6ff8823
I/art     (15174): ::: d32795a e78ddf3 976a748 888e93e a22d541
I/art     (15174): ::: ce83e31 8c1527a 12eb0c5 645e477 dfe7809
I/art     (15174): ::: eabb3d3 47d522b 15b7c90 d5d58ec ba65681
I/art     (15174): ::: ae44441 280f32b 71c018d d3997bd 254b85e
I/art     (15174): ::: 4e9c4e7 33bac5c 41be588 25adcfb 204b0a4
I/art     (15174): ::: 894f3fd 69adbe2 949ce9c b47a1cc c14d38e
I/art     (15174): ::: bc48984 c90450a 928dc3c dc1aac8 e4a2f0
I/art     (15174): ::: 91373ca 5b5ee2a 819765b c770fe0 250a966
I/art     (15174): ::: db16f2a 9b583a2 a 0 0
```

**Comment by bernardosaltiel** [comment]
> @jhonathanqz estou tendo o mesmo problema mesmo utilizando a sua versão com a correção
> 
> ```
> I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: No Key event currently.
> I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: Previeous Event null,finish at 1969-12-31 21:00:00.000
> I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: No motion event currently.
> I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: Previeous Event MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=365.0, y[0]=1211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100231397, downTime=100231307, deviceId=0, source=0x1002 },finish at 2024-05-14 19:15:24.354
> I/art     (15174): Thread[3,tid=15180,WaitingInMainSignalCatcherLoop,Thread*=0xa03cb300,peer=0x12cc6b80,"Signal Catcher"]: reacting to signal 3
> I/art     (15174): 
> I/art     (15174): Wrote stack traces to '/data/anr/traces.txt'
> I/art     (15174): ::: 84262ec 9e856d bb31492 94208d 9bfbd7c
> I/art     (15174): ::: 6f25558 ad72bf9 264a0f0 4bd579f 6ff8823
> I/art     (15174): ::: d32795a e78ddf3 976a748 888e93e a22d541
> I/art     (15174): ::: ce83e31 8c1527a 12eb0c5 645e477 dfe7809
> I/art     (15174): ::: eabb3d3 47d522b 15b7c90 d5d58ec ba65681
> I/art     (15174): ::: ae44441 280f32b 71c018d d3997bd 254b85e
> I/art     (15174): ::: 4e9c4e7 33bac5c 41be588 25adcfb 204b0a4
> I/art     (15174): ::: 894f3fd 69adbe2 949ce9c b47a1cc c14d38e
> I/art     (15174): ::: bc48984 c90450a 928dc3c dc1aac8 e4a2f0
> I/art     (15174): ::: 91373ca 5b5ee2a 819765b c770fe0 250a966
> I/art     (15174): ::: db16f2a 9b583a2 a 0 0
> ```

Estamos fazendo a implantação tambem aqui e estamos enfrentando a mesma situação, teve algum cenario para contornar o mesmo? já tentamos varias coisas e nada

**Comment by bernardosaltiel** [comment]
@jhonathanqz tem previsão de quando vai conseguir dar uma olhada nisso?

**Comment by Guimarte** [comment]
> @jhonathanqz estou tendo o mesmo problema mesmo utilizando a sua versão com a correção
> 
> ```
> I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: No Key event currently.
> I/ViewRootImpl[MainActivity](15174): ANR Key Analyze: Previeous Event null,finish at 1969-12-31 21:00:00.000
> I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: No motion event currently.
> I/ViewRootImpl[MainActivity](15174): ANR Motion Analyze: Previeous Event MotionEvent { action=ACTION_UP, actionButton=0, id[0]=0, x[0]=365.0, y[0]=1211.0, toolType[0]=TOOL_TYPE_FINGER, buttonState=0, metaState=0, flags=0x0, edgeFlags=0x0, pointerCount=1, historySize=0, eventTime=100231397, downTime=100231307, deviceId=0, source=0x1002 },finish at 2024-05-14 19:15:24.354
> I/art     (15174): Thread[3,tid=15180,WaitingInMainSignalCatcherLoop,Thread*=0xa03cb300,peer=0x12cc6b80,"Signal Catcher"]: reacting to signal 3
> I/art     (15174): 
> I/art     (15174): Wrote stack traces to '/data/anr/traces.txt'
> I/art     (15174): ::: 84262ec 9e856d bb31492 94208d 9bfbd7c
> I/art     (15174): ::: 6f25558 ad72bf9 264a0f0 4bd579f 6ff8823
> I/art     (15174): ::: d32795a e78ddf3 976a748 888e93e a22d541
> I/art     (15174): ::: ce83e31 8c1527a 12eb0c5 645e477 dfe7809
> I/art     (15174): ::: eabb3d3 47d522b 15b7c90 d5d58ec ba65681
> I/art     (15174): ::: ae44441 280f32b 71c018d d3997bd 254b85e
> I/art     (15174): ::: 4e9c4e7 33bac5c 41be588 25adcfb 204b0a4
> I/art     (15174): ::: 894f3fd 69adbe2 949ce9c b47a1cc c14d38e
> I/art     (15174): ::: bc48984 c90450a 928dc3c dc1aac8 e4a2f0
> I/art     (15174): ::: 91373ca 5b5ee2a 819765b c770fe0 250a966
> I/art     (15174): ::: db16f2a 9b583a2 a 0 0
> ```

Conseguiu resolver de alguma maneira?

**Comment by jhonathanqz** [comment]
Pessoal foi implementado um novo método de impressão na branch "fix/printer-file". Por favor, testem com essa branch o método "printerFile", ele está seguindo o repositório de exemplo da pagseguro. Obrigatóriamente o arquivo deve estar na pasta download.

O parametro "fileName" deve seguir o nome do arquivo junto da extensão. Ex: teste_pagseguro.jpeg

<img width="850" alt="new impressao pagseguro" src="https://github.com/gabuldev/pagseguro_smart_flutter/assets/74057391/e68df097-6b71-41f6-8ed1-5f55dbfc2466">

**Comment by muriloventuroso** [comment]
Pra mim funcionou, obrigado!

**Comment by jhonathanqz** [comment]
Foi liberado 3 métodos de impressão:

- printerfromFile(path) ==> passar path absoluto do arquivo como parametro.
- printerFile(fileName) ==> Passar nome do arquivo com extensão como parametro.
- printer(path) ==> Passar path absoluto do arquivo como parametro.

Fechando a issue
